apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nfs
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: nfs
subjects:
- kind: ServiceAccount
  name: default   # Cambia questo se stai usando un service account diverso
  namespace: default
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io

