apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
  namespace: nfs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: nfs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod
  namespace: nfs
