apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
  namespace: nfs
  annotations:
    kubernetes.io/service-account.name: dev
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: nfs
  annotations:
    kubernetes.io/service-account.name: test
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: prod-secret
  namespace: nfs
  annotations:
    kubernetes.io/service-account.name: prod
type: kubernetes.io/service-account-token
