apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "envd-server.tensorchord.ai"
  annotations:
    cert-manager.io/inject-ca-from: default/envd-server-pod-webhook-certificate
webhooks:
  - name: "envd-server.tensorchord.ai"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: envd-server-pod-webhook
        path: /validate-pods
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
